import os
import subprocess
aqui = os.getcwd()
lista = os.listdir(aqui)

def get_wb(string):
	content = string.split("\n")
	d = []
	for l in content:
		if "cell" in l:
			d.append(l)
	return d

for f in lista:
	print f,
	nam, ext = f.split(".")
	print nam, ext
	if ext == 'prmtop':
		with open(nam + "_vmd_extract", "w") as extractor:
			xtr = """mol new ./{0}.prmtop
mol addfile ./{0}.inpcrd type rst7 top
source VMD_cell.tcl
get_cell
mol delete top
quit""".format(nam)
			extractor.write(xtr)
		vwb = subprocess.check_output(["vmd","-dispdev","text","-e",nam + "_vmd_extract"])
		os.remove(nam + "_vmd_extract")
		wb = get_wb(vwb)
		if not os.path.exists(aqui + "/" + nam):
			os.makedirs(aqui + "/" + nam)
		with open(nam + ".namd", "w") as dinamico:
			inp = """# NAMD Config file - autogenerated by Rony's Script
# Author: Rony Letona,  zronyj@gmail.com

# input
amber                   yes
ambercoor               {6}/{0}.inpcrd
parmfile                {6}/{0}.prmtop
readexclusions          off
scnb                    2
rigidBonds              all
rigidTolerance          0.0005
PME                     on

#periodic cell
{2}
{3}
{4}
{5}

PMEGridSizeX            160
PMEGridSizeY            160
PMEGridSizeZ            160

# output
set output              {6}/{0}/{0}
outputname              $output
dcdfile                 ${1}.dcd
xstFile                 ${1}.xst
dcdfreq                 50
xstFreq                 50

binaryoutput            no
binaryrestart           no
outputEnergies          100
restartfreq             1000

fixedAtoms              off

# Basic dynamics
exclude                 scaled1-4
1-4scaling              0.833333
COMmotion               no
dielectric              1.0

# Simulation space partitioning
switching               off
switchdist              9
cutoff                  9
pairlistdist            12

# Multiple timestepping
firsttimestep           0
timestep                1
stepspercycle           20
nonbondedFreq           2
fullElectFrequency      4

# Temperature control

set temperature         298
temperature             $temperature;  # initial temperature


# Scripting

minimize            1000
reinitvels          $temperature
run                 10000""".format(nam, "{output}", wb[0], wb[1], wb[2], wb[3], aqui)
			dinamico.write(inp)
